# file created: 2024-02-19 05:37:00.820771

# this files has been generated by CandyTranslate.com  Please do not change manually
# author: Next Level Sense

# Available functions:
#    render - replacement for django render function
#    path - replacement for django path function. please use with * when replacing in urls.py
#    supported_languages - list that contains all available languages for this site
# Functions to be used in django templates:
#    languageReferences - create 'alternate' language references for SEO.
#        put it inside of the <head> section of the page in format {{languageReferences|safe}}
#    lang - current language. Used mostly in <html lang="{{lang}}">
#    languageMenu - adding language selection for your page. Format: {{languageMenu|safe}}
#    <<link variables>> - create linking to correct language link. 
#    usage:
#    for translated pages change {% url "my_page" %}
#    to name without quotes:     {% url my_page %}


supported_languages = ['en', 'ar', 'bn', 'de', 'hi', 'pa', 'ta', 'ur']

def translation_dictionary(lang):
    if lang == 'en': return {
        'index_signup':'''Signup''',
        'index_login':'''login''',
        'index_Home':'''Home''',
        'index_about':'''about''',
        'index_bookTickets':'''book Tickets''',
        'index_contact':'''contact''',
        'index_Letthe':'''Let the''',
        'index_World':'''World''',
        'index_play':'''play''',
        'index_ssportigo':'''@sportigo''',
        'index_playwith':'''PLAY WITH US ! ''',
        'index_Bookslot':'''Book slot''',
        'index_TOgetlisted':'''TO get listed''',
        'index_About1':'''About''',
        'index_sportigo':'''sportigo''',
        'index_sp1':'''Are you a football club looking for hassle-free turf bookings? Register with us today and enjoy exclusive benefits such as bulk booking discounts, priority access to premium turf slots, and personalized booking assistance!''',
        'index_Register':'''Register''',
        'index_FillTheForm':'''Fill The Form''',
        'index_Clubs':'''Clubs''',
        'index_arein':'''are in''',
        'index_Whyareyouwaiting':'''Why are you waiting''',
        'index_Explore':'''Explore''',
        'index_des1':'''Sportigo is the ultimate turf booking app designed to cater to football enthusiasts everywhere. With Sportigo, you can easily discover and reserve nearby football turfs in various locations. Our user-friendly interface and real-time availability updates ensure that you can quickly find the perfect pitch for your game, check prices, and secure your booking with just a few taps. Dont waste time searching for available pitches – let Sportigo connect you to the best football turfs for your matches''',
        'index_clubdes':'''EXCITING CLUB FEATURES & EXCLUSIVE BENEFITS''',
        'index_get':'''Get Verified''',
        'index_exp':'''Explore''',
        'index_join':'''Join Now''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'ar': return {
        'index_signup':'''اشتراك''',
        'index_login':'''تسجيل الدخول''',
        'index_Home':'''بيت''',
        'index_about':'''عن''',
        'index_bookTickets':'''تذاكر الكتاب''',
        'index_contact':'''اتصال''',
        'index_Letthe':'''السماح لل''',
        'index_World':'''عالم''',
        'index_play':'''يلعب''',
        'index_ssportigo':'''sportigo''',
        'index_playwith':'''العب معنا !''',
        'index_Bookslot':'''فتحة الكتاب''',
        'index_TOgetlisted':'''للحصول على القائمة''',
        'index_About1':'''عن''',
        'index_sportigo':'''Sportigo''',
        'index_sp1':'''هل أنت نادي كرة قدم تبحث عن حجوزات العشب الخالية من المتاعب؟ سجل معنا اليوم واستمتع بمزايا حصرية مثل خصومات الحجز بالجملة ، والوصول ذي الأولوية إلى فتحات العشب الممتازة ، ومساعدة الحجز المخصصة!''',
        'index_Register':'''يسجل''',
        'index_FillTheForm':'''املأ النموذج''',
        'index_Clubs':'''الأندية''',
        'index_arein':'''يكون في''',
        'index_Whyareyouwaiting':'''لماذا تنتظر''',
        'index_Explore':'''يستكشف''',
        'index_des1':'''Sportigo هو التطبيق النهائي لحجز العشب المصمم لتلبية احتياجات عشاق كرة القدم في كل مكان. مع Sportigo، يمكنك بسهولة اكتشاف وحجز ملاعب كرة القدم القريبة في مواقع مختلفة. تضمن واجهتنا سهلة الاستخدام وتحديثات التوفر في الوقت الفعلي إمكانية العثور بسرعة على الملعب المثالي للعبتك والتحقق من الأسعار وتأمين حجزك ببضع نقرات فقط. لا تضيع وقتك في البحث عن الملاعب المتاحة – اسمح لـ Sportigo بتوصيلك بأفضل ملاعب كرة القدم لمبارياتك''',
        'index_clubdes':'''الأندية''',
        'index_get':'''يكون في''',
        'index_exp':'''لماذا تنتظر''',
        'index_join':'''يستكشف''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'bn': return {
        'index_signup':'''নিবন্ধন করুন''',
        'index_login':'''প্রবেশ করুন''',
        'index_Home':'''বাড়ি''',
        'index_about':'''সম্পর্কিত''',
        'index_bookTickets':'''আমার স্নাতকের''',
        'index_contact':'''যোগাযোগ''',
        'index_Letthe':'''দিন''',
        'index_World':'''বিশ্ব''',
        'index_play':'''খেলুন''',
        'index_ssportigo':'''@স্পোর্টিগো''',
        'index_playwith':'''আমাদের সাথে খেলুন !''',
        'index_Bookslot':'''বই স্লট''',
        'index_TOgetlisted':'''তালিকাভুক্ত পেতে''',
        'index_About1':'''সম্পর্কিত''',
        'index_sportigo':'''স্পোর্টিগো''',
        'index_sp1':'''আপনি কি কোনও ফুটবল ক্লাব ঝামেলা-মুক্ত টার্ফ বুকিং খুঁজছেন? আজই আমাদের সাথে নিবন্ধন করুন এবং একচেটিয়া সুবিধা যেমন বাল্ক বুকিং ছাড়, প্রিমিয়াম টার্ফ স্লটে অগ্রাধিকার অ্যাক্সেস এবং ব্যক্তিগতকৃত বুকিং সহায়তা উপভোগ করুন!''',
        'index_Register':'''নিবন্ধন''',
        'index_FillTheForm':'''ফর্মটি পূরণ করুন''',
        'index_Clubs':'''ক্লাব''',
        'index_arein':'''আছে''',
        'index_Whyareyouwaiting':'''কেন আপনি অপেক্ষা করছে''',
        'index_Explore':'''অন্বেষণ''',
        'index_des1':'''Sportigo হল চূড়ান্ত টার্ফ বুকিং অ্যাপ যা সর্বত্র ফুটবল ভক্তদের চাহিদা মেটাতে ডিজাইন করা হয়েছে। স্পোর্টিগোর মাধ্যমে, আপনি সহজেই বিভিন্ন স্থানে কাছাকাছি ফুটবল স্টেডিয়ামগুলি আবিষ্কার করতে এবং বুক করতে পারেন৷ আমাদের সহজে-ব্যবহারযোগ্য ইন্টারফেস এবং রিয়েল-টাইম প্রাপ্যতা আপডেটগুলি নিশ্চিত করে যে আপনি দ্রুত আপনার গেমের জন্য নিখুঁত স্টেডিয়াম খুঁজে পেতে পারেন, দাম পরীক্ষা করতে পারেন এবং মাত্র কয়েকটি ক্লিকের মাধ্যমে আপনার রিজার্ভেশন সুরক্ষিত করতে পারেন। উপলব্ধ স্টেডিয়ামগুলি খুঁজতে আপনার সময় নষ্ট করবেন না – স্পোর্টিগোকে আপনার ম্যাচের জন্য সেরা ফুটবল স্টেডিয়ামগুলির সাথে সংযোগ করতে দিন''',
        'index_clubdes':'''ক্লাব''',
        'index_get':'''আছে''',
        'index_exp':'''কেন আপনি অপেক্ষা করছে''',
        'index_join':'''অন্বেষণ''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'de': return {
        'index_signup':'''Melden Sie sich an''',
        'index_login':'''Anmeldung''',
        'index_Home':'''Heim''',
        'index_about':'''um''',
        'index_bookTickets':'''Buchkarten''',
        'index_contact':'''Kontakt''',
        'index_Letthe':'''Lassen Sie die''',
        'index_World':'''Welt''',
        'index_play':'''spielen''',
        'index_ssportigo':'''@Sportigo''',
        'index_playwith':'''SPIELE MIT UNS !''',
        'index_Bookslot':'''Buchschlitz''',
        'index_TOgetlisted':'''Aufgelistet werden''',
        'index_About1':'''Um''',
        'index_sportigo':'''Sportigo''',
        'index_sp1':'''Sind Sie ein Fußballverein, der nach problemlosen Rasenbuchungen sucht? Registrieren Sie sich noch heute bei uns und genießen Sie exklusive Vorteile wie Rabatte mit Massenbuchung, vorrangiger Zugang zu Premium -Rasen -Slots und personalisierte Buchungsunterstützung!''',
        'index_Register':'''Registrieren''',
        'index_FillTheForm':'''Fülle das Formular aus''',
        'index_Clubs':'''Clubs''',
        'index_arein':'''sind in''',
        'index_Whyareyouwaiting':'''Warum wartest du''',
        'index_Explore':'''Erkunden''',
        'index_des1':'''Sportigo ist die ultimative App zur Platzbuchung, die speziell auf die Bedürfnisse von Fußballfans auf der ganzen Welt zugeschnitten ist. Mit Sportigo können Sie ganz einfach nahegelegene Fußballstadien an verschiedenen Standorten entdecken und buchen. Unsere benutzerfreundliche Oberfläche und Verfügbarkeitsaktualisierungen in Echtzeit stellen sicher, dass Sie mit nur wenigen Klicks schnell das perfekte Stadion für Ihr Spiel finden, Preise prüfen und Ihre Reservierung sichern können. Verschwenden Sie keine Zeit mit der Suche nach verfügbaren Stadien – lassen Sie sich von Sportigo mit den besten Fußballstadien für Ihre Spiele verbinden''',
        'index_clubdes':'''Clubs''',
        'index_get':'''sind in''',
        'index_exp':'''Warum wartest du''',
        'index_join':'''Erkunden''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'hi': return {
        'index_signup':'''साइन अप करें''',
        'index_login':'''लॉग इन करें''',
        'index_Home':'''घर''',
        'index_about':'''के बारे में''',
        'index_bookTickets':'''टिकट बनाओ''',
        'index_contact':'''संपर्क''',
        'index_Letthe':'''होने दें''',
        'index_World':'''दुनिया''',
        'index_play':'''खेल''',
        'index_ssportigo':'''@sportigo''',
        'index_playwith':'''हमारे साथ खेलते हैं !''',
        'index_Bookslot':'''बुक स्लॉट''',
        'index_TOgetlisted':'''सूचीबद्ध होने के लिए''',
        'index_About1':'''के बारे में''',
        'index_sportigo':'''स्पोर्टिगो''',
        'index_sp1':'''क्या आप एक फुटबॉल क्लब परेशानी मुक्त टर्फ बुकिंग की तलाश कर रहे हैं? आज हमारे साथ पंजीकरण करें और विशेष लाभों का आनंद लें जैसे कि बल्क बुकिंग छूट, प्रीमियम टर्फ स्लॉट तक प्राथमिकता पहुंच, और व्यक्तिगत बुकिंग सहायता!''',
        'index_Register':'''पंजीकरण करवाना''',
        'index_FillTheForm':'''प्रपत्र भरिये''',
        'index_Clubs':'''क्लब''',
        'index_arein':'''में हैं''',
        'index_Whyareyouwaiting':'''तुम क्यों इंतजार कर रहे हो''',
        'index_Explore':'''अन्वेषण करना''',
        'index_des1':'''स्पोर्टिगो हर जगह फुटबॉल प्रशंसकों की जरूरतों को पूरा करने के लिए डिज़ाइन किया गया अंतिम टर्फ बुकिंग ऐप है। स्पोर्टिगो के साथ, आप विभिन्न स्थानों में आस-पास के फुटबॉल स्टेडियमों को आसानी से खोज और बुक कर सकते हैं। हमारा उपयोग में आसान इंटरफ़ेस और वास्तविक समय उपलब्धता अपडेट यह सुनिश्चित करते हैं कि आप अपने खेल के लिए तुरंत सही स्टेडियम ढूंढ सकें, कीमतों की जांच कर सकें और कुछ ही क्लिक के साथ अपना आरक्षण सुरक्षित कर सकें। उपलब्ध स्टेडियमों की खोज में अपना समय बर्बाद न करें - स्पोर्टिगो को आपके मैचों के लिए सर्वश्रेष्ठ फुटबॉल स्टेडियमों से जोड़ने दें''',
        'index_clubdes':'''क्लब''',
        'index_get':'''में हैं''',
        'index_exp':'''तुम क्यों इंतजार कर रहे हो''',
        'index_join':'''अन्वेषण करना''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'pa': return {
        'index_signup':'''ਸਾਇਨ ਅਪ''',
        'index_login':'''ਲਾਗਿਨ''',
        'index_Home':'''ਘਰ''',
        'index_about':'''ਬਾਰੇ''',
        'index_bookTickets':'''ਕਿਤਾਬ ਦੀਆਂ ਟਿਕਟਾਂ''',
        'index_contact':'''ਸੰਪਰਕ''',
        'index_Letthe':'''ਨੂੰ ਚਾਹੀਦਾ ਹੈ''',
        'index_World':'''ਵਿਸ਼ਵ''',
        'index_play':'''ਖੇਡੋ''',
        'index_ssportigo':'''@ ਐਸਪੋਰਟਗੋ''',
        'index_playwith':'''ਸਾਡੇ ਨਾਲ ਖੇਡੋ!''',
        'index_Bookslot':'''ਕਿਤਾਬ ਸਲਾਟ''',
        'index_TOgetlisted':'''ਸੂਚੀਬੱਧ ਹੋਣ ਲਈ''',
        'index_About1':'''ਬਾਰੇ''',
        'index_sportigo':'''ਸਪੋਰਟਿਗੋ''',
        'index_sp1':'''ਕੀ ਤੁਸੀਂ ਫੁਟਬਾਲ ਕਲੱਬ ਨੂੰ ਮੁਸ਼ਕਲ ਰਹਿਤ ਮੈਦਾਨ ਦੀ ਬੁਕਿੰਗ ਦੀ ਭਾਲ ਕਰ ਰਹੇ ਹੋ? ਅੱਜ ਸਾਡੇ ਨਾਲ ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਵਿਸ਼ੇਸ਼ ਲਾਭਾਂ ਦਾ ਅਨੰਦ ਲਓ ਜਿਵੇਂ ਕਿ ਥੋਕ ਬੁਕਿੰਗ ਛੋਟ, ਪ੍ਰੀਮੀਅਮ ਮੈਦਾਨ ਦੀਆਂ ਸਲੋਟਾਂ, ਅਤੇ ਵਿਅਕਤੀਗਤ ਬੁਕਿੰਗ ਸਹਾਇਤਾ ਪ੍ਰਾਪਤ ਕਰਨ ਤੋਂ ਜ਼ਰੂਰੀ ਪਹੁੰਚ!''',
        'index_Register':'''ਰਜਿਸਟਰ''',
        'index_FillTheForm':'''ਫਾਰਮ ਭਰੋ''',
        'index_Clubs':'''ਕਲੱਬਾਂ''',
        'index_arein':'''ਵਿੱਚ ਹਨ''',
        'index_Whyareyouwaiting':'''ਤੁਸੀਂ ਇੰਤਜ਼ਾਰ ਕਿਉਂ ਕਰ ਰਹੇ ਹੋ''',
        'index_Explore':'''ਪੜਚੋਲ''',
        'index_des1':'''Sportigo ਹਰ ਜਗ੍ਹਾ ਫੁੱਟਬਾਲ ਪ੍ਰਸ਼ੰਸਕਾਂ ਦੀਆਂ ਜ਼ਰੂਰਤਾਂ ਨੂੰ ਪੂਰਾ ਕਰਨ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਆਖਰੀ ਟਰਫ ਬੁਕਿੰਗ ਐਪ ਹੈ। ਸਪੋਰਟਿਗੋ ਦੇ ਨਾਲ, ਤੁਸੀਂ ਆਸਾਨੀ ਨਾਲ ਵੱਖ-ਵੱਖ ਥਾਵਾਂ 'ਤੇ ਨੇੜਲੇ ਫੁੱਟਬਾਲ ਸਟੇਡੀਅਮਾਂ ਨੂੰ ਖੋਜ ਅਤੇ ਬੁੱਕ ਕਰ ਸਕਦੇ ਹੋ। ਸਾਡੇ ਆਸਾਨ-ਵਰਤਣ ਵਾਲੇ ਇੰਟਰਫੇਸ ਅਤੇ ਰੀਅਲ-ਟਾਈਮ ਉਪਲਬਧਤਾ ਅੱਪਡੇਟ ਇਹ ਯਕੀਨੀ ਬਣਾਉਂਦੇ ਹਨ ਕਿ ਤੁਸੀਂ ਆਪਣੀ ਗੇਮ ਲਈ ਸਹੀ ਸਟੇਡੀਅਮ ਲੱਭ ਸਕਦੇ ਹੋ, ਕੀਮਤਾਂ ਦੀ ਜਾਂਚ ਕਰ ਸਕਦੇ ਹੋ ਅਤੇ ਕੁਝ ਕੁ ਕਲਿੱਕਾਂ ਨਾਲ ਆਪਣਾ ਰਿਜ਼ਰਵੇਸ਼ਨ ਸੁਰੱਖਿਅਤ ਕਰ ਸਕਦੇ ਹੋ। ਉਪਲਬਧ ਸਟੇਡੀਅਮਾਂ ਦੀ ਖੋਜ ਕਰਨ ਵਿੱਚ ਆਪਣਾ ਸਮਾਂ ਬਰਬਾਦ ਨਾ ਕਰੋ – ਸਪੋਰਟਿਗੋ ਨੂੰ ਤੁਹਾਡੇ ਮੈਚਾਂ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਫੁੱਟਬਾਲ ਸਟੇਡੀਅਮਾਂ ਨਾਲ ਜੁੜਨ ਦਿਓ''',
        'index_clubdes':'''ਕਲੱਬਾਂ''',
        'index_get':'''ਵਿੱਚ ਹਨ''',
        'index_exp':'''ਤੁਸੀਂ ਇੰਤਜ਼ਾਰ ਕਿਉਂ ਕਰ ਰਹੇ ਹੋ''',
        'index_join':'''ਪੜਚੋਲ''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'ta': return {
        'index_signup':'''பதிவுபெறுதல்''',
        'index_login':'''உள்நுழைய''',
        'index_Home':'''வீடு''',
        'index_about':'''பற்றி''',
        'index_bookTickets':'''பயணசீட்டை பதிவுசெய்''',
        'index_contact':'''தொடர்பு''',
        'index_Letthe':'''விடுங்கள்''',
        'index_World':'''உலகம்''',
        'index_play':'''விளையாடுங்கள்''',
        'index_ssportigo':'''@sportigo''',
        'index_playwith':'''எங்களுடன் விளையாடுங்கள்!''',
        'index_Bookslot':'''புத்தக ஸ்லாட்''',
        'index_TOgetlisted':'''பட்டியலிட''',
        'index_About1':'''பற்றி''',
        'index_sportigo':'''ஸ்போர்டிகோ''',
        'index_sp1':'''நீங்கள் தொந்தரவு இல்லாத தரை முன்பதிவுகளைத் தேடும் ஒரு கால்பந்து கிளப்பா? இன்று எங்களுடன் பதிவுசெய்து, மொத்தமாக முன்பதிவு தள்ளுபடிகள், பிரீமியம் தரை இடங்களுக்கு முன்னுரிமை அணுகல் மற்றும் தனிப்பயனாக்கப்பட்ட முன்பதிவு உதவி போன்ற பிரத்யேக நன்மைகளை அனுபவிக்கவும்!''',
        'index_Register':'''பதிவு''',
        'index_FillTheForm':'''படிவத்தை நிரப்புக''',
        'index_Clubs':'''கிளப்புகள்''',
        'index_arein':'''இல் உள்ளன''',
        'index_Whyareyouwaiting':'''நீங்கள் ஏன் காத்திருக்கிறீர்கள்''',
        'index_Explore':'''ஆராயுங்கள்''',
        'index_des1':'''ஸ்போர்டிகோ என்பது எல்லா இடங்களிலும் உள்ள கால்பந்து ரசிகர்களின் தேவைகளைப் பூர்த்தி செய்யும் வகையில் வடிவமைக்கப்பட்ட இறுதி தரை முன்பதிவு பயன்பாடாகும். Sportigo மூலம், வெவ்வேறு இடங்களில் அருகிலுள்ள கால்பந்து மைதானங்களை எளிதாகக் கண்டுபிடித்து முன்பதிவு செய்யலாம். எங்களின் சுலபமாக பயன்படுத்தக்கூடிய இடைமுகம் மற்றும் நிகழ்நேரக் கிடைக்கும் புதுப்பிப்புகள், உங்கள் விளையாட்டுக்கான சரியான மைதானத்தை விரைவாகக் கண்டறியலாம், விலைகளைச் சரிபார்த்து, சில கிளிக்குகளில் உங்கள் முன்பதிவைப் பாதுகாக்கலாம். கிடைக்கக்கூடிய மைதானங்களைத் தேடி உங்கள் நேரத்தை வீணாக்காதீர்கள் – உங்கள் போட்டிகளுக்கான சிறந்த கால்பந்து மைதானங்களுடன் Sportigo உங்களை இணைக்கட்டும்''',
        'index_clubdes':'''கிளப்புகள்''',
        'index_get':'''இல் உள்ளன''',
        'index_exp':'''நீங்கள் ஏன் காத்திருக்கிறீர்கள்''',
        'index_join':'''ஆராயுங்கள்''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }
    if lang == 'ur': return {
        'index_signup':'''سائن اپ''',
        'index_login':'''لاگ ان کریں''',
        'index_Home':'''گھر''',
        'index_about':'''کے بارے میں''',
        'index_bookTickets':'''سائن اپ''',
        'index_contact':'''لاگ ان کریں''',
        'index_Letthe':'''گھر''',
        'index_World':'''کے بارے میں''',
        'index_play':'''ٹکٹ کٹاؤ''',
        'index_ssportigo':'''رابطہ کریں''',
        'index_playwith':'''جانے دو''',
        'index_Bookslot':'''دنیا''',
        'index_TOgetlisted':'''کھیلیں''',
        'index_About1':'''@سپورٹیگو''',
        'index_sportigo':'''ہمارے ساتھ کھیلو!''',
        'index_sp1':'''کتاب سلاٹ''',
        'index_Register':'''درج ہونے کے لئے''',
        'index_FillTheForm':'''کے بارے میں''',
        'index_Clubs':'''اسپورٹیگو''',
        'index_arein':'''کیا آپ فٹ بال کلب پریشانی سے پاک ٹرف بکنگ کی تلاش میں ہیں؟ آج ہی ہمارے ساتھ رجسٹر ہوں اور خصوصی فوائد سے لطف اٹھائیں جیسے بلک بکنگ چھوٹ ، پریمیم ٹرف سلاٹوں تک ترجیحی رسائی ، اور ذاتی نوعیت کی بکنگ امداد!''',
        'index_Whyareyouwaiting':'''اندراج کریں''',
        'index_Explore':'''فارم پُر کریں''',
        'index_des1':'''اسپورٹیگو ایک حتمی ٹرف بکنگ ایپ ہے جسے ہر جگہ فٹ بال کے شائقین کی ضروریات کو پورا کرنے کے لیے ڈیزائن کیا گیا ہے۔ Sportigo کے ساتھ، آپ آسانی سے مختلف مقامات پر قریبی فٹ بال اسٹیڈیم دریافت اور بک کر سکتے ہیں۔ ہمارا استعمال میں آسان انٹرفیس اور حقیقی وقت میں دستیابی کی تازہ کاری اس بات کو یقینی بناتی ہے کہ آپ اپنے کھیل کے لیے فوری طور پر بہترین اسٹیڈیم تلاش کر سکتے ہیں، قیمتیں چیک کر سکتے ہیں اور صرف چند کلکس کے ذریعے اپنی ریزرویشن محفوظ کر سکتے ہیں۔ دستیاب اسٹیڈیموں کی تلاش میں اپنا وقت ضائع نہ کریں - اسپورٹیگو کو آپ کو اپنے میچوں کے لیے بہترین فٹ بال اسٹیڈیم سے جوڑنے دیں''',
        'index_clubdes':'''کلب''',
        'index_get':'''میں ہیں''',
        'index_exp':'''آپ کیوں انتظار کر رہے ہیں؟''',
        'index_join':'''دریافت کریں''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        'index_nan':'''nan''',
        }


def detectLanguage(request):
    languageDetected = supported_languages[0]
    pagePath = request.path
    if pagePath[-1] == '/': pagePath=pagePath[:-1]
    pagePath = pagePath.split('?')[0]
    pagePath = pagePath.split('#')[0]
    lastPath = pagePath.split('/')[-1]
    if lastPath in supported_languages[1:]:
        languageDetected = lastPath
    return languageDetected


def translated(requestOrLang,TranslateVariable):
    if requestOrLang in supported_languages:
        lang=requestOrLang
    else:
        lang = detectLanguage(requestOrLang)
    return translation_dictionary(lang)[TranslateVariable]


def localizeLink(request, link):
    lang=detectLanguage(request)
    if lang == supported_languages[0]: return link
    index1 = link.find('#')
    index2 = link.find('?')
    if index1 == -1 and index2 == -1: smallest_index = len(link)
    elif index1 == -1: smallest_index = index2
    elif index2 == -1: smallest_index = index1
    else: smallest_index = min(index1, index2)
    path = link[:smallest_index]
    if path[-1] == '/': path=path[:-1]
    return path+'/'+lang+link[smallest_index:]


from django.shortcuts import redirect as org_redirect
def redirect(request, to, *args, permanent=False, **kwargs):
    lang=detectLanguage(request)
    if lang in supported_languages[1:]:
        to=to+'_'+lang
    return org_redirect(to, *args, permanent=permanent, **kwargs)


from django.urls import path as org_path
def path(route, view, kwargs=None, name=None):
    if route == '':
        return [org_path('', view, kwargs, name),org_path('ar', view, kwargs, name+'_ar'),org_path('bn', view, kwargs, name+'_bn'),org_path('de', view, kwargs, name+'_de'),org_path('hi', view, kwargs, name+'_hi'),org_path('pa', view, kwargs, name+'_pa'),org_path('ta', view, kwargs, name+'_ta'),org_path('ur', view, kwargs, name+'_ur'),]
    if route[-1] == '/': route=route[:-1]
    return [org_path(route, view, kwargs, name),org_path(route+'/ar', view, kwargs, name+'_ar'),org_path(route+'/bn', view, kwargs, name+'_bn'),org_path(route+'/de', view, kwargs, name+'_de'),org_path(route+'/hi', view, kwargs, name+'_hi'),org_path(route+'/pa', view, kwargs, name+'_pa'),org_path(route+'/ta', view, kwargs, name+'_ta'),org_path(route+'/ur', view, kwargs, name+'_ur'),]


def langRef(path_ref):
    last=path_ref.split('/')[-1]
    if last in supported_languages:
        path_ref=path_ref[:-len(last)-1]
    result='<link rel="alternate" hreflang="en" href="'+addLinks(path_ref,'')+'" />\n'
    result+='<link rel="alternate" hreflang="ar" href="'+addLinks(path_ref,'ar')+'" />\n'
    result+='<link rel="alternate" hreflang="bn" href="'+addLinks(path_ref,'bn')+'" />\n'
    result+='<link rel="alternate" hreflang="de" href="'+addLinks(path_ref,'de')+'" />\n'
    result+='<link rel="alternate" hreflang="hi" href="'+addLinks(path_ref,'hi')+'" />\n'
    result+='<link rel="alternate" hreflang="pa" href="'+addLinks(path_ref,'pa')+'" />\n'
    result+='<link rel="alternate" hreflang="ta" href="'+addLinks(path_ref,'ta')+'" />\n'
    result+='<link rel="alternate" hreflang="ur" href="'+addLinks(path_ref,'ur')+'" />\n'
    result+='<link rel="alternate" hreflang="x-default" href="'+addLinks(path_ref,'')+'" />\n'
    return result


from django.urls import get_resolver
def translatedLinks(lang):
    names=[]
    for i in get_resolver().url_patterns:
        if hasattr(i, 'name'):
            if i.name:
                names.append(i.name)
    result = {}
    if lang == supported_languages[0]:
        for i in names:
            if i[-3:] not in ['_ar', '_bn', '_de', '_hi', '_pa', '_ta', '_ur'] and names.count(i+'_ar'):
                result.update({i:i})
        return result
    for i in names:
        if names.count(i+'_'+lang):
            result.update({i:i+'_'+lang})
    return result


def languageMenu(request, lang):
    path = request.path
    remainder = request.get_full_path()[len(path):]
    selected = [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
    selected[supported_languages.index(lang)]=' selected '
    if supported_languages.index(lang):
        path=path[:-3]
    result = '<select id="languageMenu" onchange="window.location = this.value;">'
    if path == '/': path = ''
    if path =='':
        result += '<option'+selected[0]+'value="/'+remainder+'">English (English)</option>'
    else:
        result += '<option'+selected[0]+'value="' + path + remainder +'">English (English)</option>'
    result += '<option'+selected[1]+'value="' + path +'/ar'+remainder+'">Arabic (العربية)</option>'
    result += '<option'+selected[2]+'value="' + path +'/bn'+remainder+'">Bengali (বাংলা)</option>'
    result += '<option'+selected[3]+'value="' + path +'/de'+remainder+'">German (Deutsch)</option>'
    result += '<option'+selected[4]+'value="' + path +'/hi'+remainder+'">Hindi (हिन्दी)</option>'
    result += '<option'+selected[5]+'value="' + path +'/pa'+remainder+'">Punjabi (ਪੰਜਾਬੀ)</option>'
    result += '<option'+selected[6]+'value="' + path +'/ta'+remainder+'">Tamil (தமிழ்)</option>'
    result += '<option'+selected[7]+'value="' + path +'/ur'+remainder+'">Urdu (اردو)</option>'
    result += '</select>'
    return result


from django.shortcuts import render as org_render
def render(request, template_name, context=None, *args, **kwargs):
    lang=detectLanguage(request)
    if context == None:
        context={}
    return org_render(request, template_name, {**context,
                                                **translation_dictionary(lang),
                                                'lang':lang,
                                                'languageReferences':langRef(request.build_absolute_uri()),
                                                'languageMenu':languageMenu(request, lang),
                                                'candyLink':translatedLinks(lang),
                                                }, *args, **kwargs)


def addLinks(*args):
    result=''
    for i in args:
        if result and result[-1]=='/':result=result[:-1]
        if i and i[-1]=='/':i=i[:-1]
        if i and i[0]=='/':i=i[1:]
        if result and i: result+='/'
        result+=i
    return result


def provideSitemap(request, add_pages=[], remove_pages=[], remove_paths=[]):
    from django.http import HttpResponse
    result='<?xml version="1.0" encoding="UTF-8"?>'+'\n'
    result+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+'\n'
    domain= request.build_absolute_uri()
    domain=domain.split('/')[0]+'//'+domain.split('/')[2]+'/'
    paths = []
    for i in get_resolver().url_patterns:
        if str(type(i))=="<class 'django.urls.resolvers.URLPattern'>":
            try:
                route=i.pattern._route
                route=route.split('<')[0]
                if not route == 'sitemap.xml':
                    if 'robots.txt' not in route:
                        paths.append(addLinks(domain,route))
            except: pass
    paths+=add_pages
    paths=list(dict.fromkeys(paths))
    for route in paths:
        removed_path = False
        for removal in remove_paths:
            if route[:len(removal)] == removal: removed_path = True
        if not removed_path and route not in remove_pages:
            result+='<url>'+'\n'
            result+='<loc>'+route+'</loc>'+'\n'
            result+='</url>'+'\n'
    result+='</urlset>'
    result= result.encode('utf-8')
    return HttpResponse(result, content_type='application/xml; charset=utf-8')


def sitemap(add_pages=[], remove_pages=[], remove_paths=[]):
    return [org_path('sitemap.xml', provideSitemap,{'add_pages' :add_pages,'remove_pages': remove_pages, 'remove_paths': remove_paths})]


