# Generated by Django 4.2.6 on 2023-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='documents/')),
                ('sports_type', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket')], max_length=10)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
