# Generated by Django 4.2.7 on 2023-11-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_turfprovider_turflisting_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turflisting',
            name='image',
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('turf_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.turflisting')),
            ],
        ),
    ]
