# Generated by Django 4.2.6 on 2023-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_turfprovider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfprovider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
