# Generated by Django 4.2.6 on 2023-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_turfprovider_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfprovider',
            name='random_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
