# Generated by Django 4.2.7 on 2024-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_clubuser_club_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='club_id',
            field=models.CharField(default='123', max_length=50, unique=True),
        ),
    ]
