# Generated by Django 4.2.7 on 2024-02-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_clubuser_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turflisting',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
