# Generated by Django 4.2.6 on 2023-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_turfprovider_password_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfprovider',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
