# Generated by Django 4.2.7 on 2024-02-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clubuser_turflisting_price_per_day'),
        ('app', '0007_turflisting_price_per_day'),
    ]

    operations = [
    ]
