# Generated by Django 4.2.6 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_turfprovider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfprovider',
            name='id',
        ),
        migrations.AlterField(
            model_name='turfprovider',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
