# Generated by Django 4.2.7 on 2023-11-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_turfprovider_id_alter_turfprovider_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=255)),
                ('sports_type', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket')], max_length=10)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turf_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.turfprovider')),
            ],
        ),
    ]
