# Generated by Django 4.2.7 on 2024-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20240222_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turflisting',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
