# Generated by Django 4.2.7 on 2023-11-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_turflisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turflisting',
            name='turf_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turfprovider'),
        ),
    ]
