# Generated by Django 4.2.7 on 2024-02-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_turflisting_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turflisting')),
                ('turf_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turfprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_bookings', to='app.clubuser')),
            ],
        ),
    ]
