# Generated by Django 4.2.7 on 2024-02-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_clubuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='club_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
