# Generated by Django 4.2.7 on 2024-02-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_clubuser_club_id_alter_clubuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='club_id',
            field=models.CharField(default='123', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
